#!/bin/sh
cd "${0%/*}" || exit
. ../../functions
#------------------------------------------------------------------------------

setImage ../../of_2106.sif

# dummy file for post-processing with paraview
touch post.foam

# mesh creation
singularityRun blockMesh
singularityRun topoSet

# set inlet velocity
cp -r 0.org 0

# decompose and run case
singularityRun decomposePar
singularityRunParallel renumberMesh -overwrite
singularityRunParallel $(getApplication)

#------------------------------------------------------------------------------
