#!/bin/bash -l    
#SBATCH --partition=standard
#SBATCH --nodes=1
#SBATCH --time=7-00:00:00
#SBATCH --job-name=100_04l
#SBATCH --ntasks-per-node=1

module load python/3.8.2

# adjust path if necessary
source ~/drlfoam/pydrl/bin/activate
source ~/drlfoam/setup-env --container

# start a training with a buffer size of 8 and 8 runners;
# save output to log.test_training
python3 run_training_pinball_100_5procs_04liftPen.py -o test_train_re100_12procs_actionmag5_5cores_140interactions_04liftPen -e slurm -b 10 -r 10 -i 20 &> log.test_training100_12procs_5cores_04liftPen
