#!/bin/bash -l    
#SBATCH --partition=standard
#SBATCH --nodes=1
#SBATCH --time=7-00:00:00
#SBATCH --job-name=100att
#SBATCH --ntasks-per-node=1
#SBATCH --error=attention100.out
#SBATCH --mem-per-cpu=8G

module load python/3.8.2

# adjust path if necessary
source ~/drlfoam/pydrl/bin/activate
source ~/drlfoam/setup-env --container

# start a training with a buffer size of 8 and 8 runners;
# save output to log.test_training
python3 run_training_pinball_attention_100.py -o test_train_attention_re100_5procs_actionmag5_baseline -e slurm -b 10 -r 10 -i 40 &> log.test_training_100_att
